import { db } from '@/lib/firebase'
import { doc, updateDoc, getDoc, collection, addDoc, Timestamp } from 'firebase/firestore'

/**
 * System Service for Admin Operations
 */

export interface SystemConfig {
    maintenanceMode: boolean
    aiEnabled: boolean
    devMode: boolean
    mockDataOverrides: boolean
}

// Dev Tools Actions
export async function toggleDevMode(enabled: boolean) {
    // In a real app, this might update a config doc in Firestore
    // For now, we'll store it in localStorage but simulated as an async operation
    if (typeof window !== 'undefined') {
        localStorage.setItem('NEXT_PUBLIC_DEV_MODE', enabled ? 'true' : 'false')
    }
    return enabled
}

export async function updateUserOnboarding(userId: string, step: number, isVerified: boolean = false) {
    try {
        const userRef = doc(db, 'users', userId)
        await updateDoc(userRef, {
            onboardingStep: step,
            isVerified: isVerified,
            updatedAt: Timestamp.now()
        })
        return { success: true, message: `Updated user ${userId} to step ${step}` }
    } catch (error: any) {
        console.error('Error updating onboarding:', error)
        return { success: false, error: error.message }
    }
}

export async function simulateAIResponse(
    prompt: string,
    type: 'description' | 'price' | 'moderation'
): Promise<any> {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 1500))

    if (type === 'description') {
        return {
            title: `AI Generated: ${prompt.substring(0, 20)}...`,
            description: `This is a simulated AI description for "${prompt}". It includes detailed specs, condition analysis, and selling points generated by the AI engine. Ideally, this would clearer and more marketing-oriented.`,
            tags: ['Simulated', 'AI', 'Test'],
            category: 'general'
        }
    }

    if (type === 'price') {
        return {
            price: Math.floor(Math.random() * 10000) + 500,
            range: { min: 500, max: 12000 },
            confidence: 0.85,
            factors: ['Brand', 'Condition', 'Market Trend']
        }
    }

    if (type === 'moderation') {
        const isSafe = !prompt.toLowerCase().includes('bad')
        return {
            flagged: !isSafe,
            reason: isSafe ? null : 'Simulated harmful content detected',
            score: isSafe ? 0.05 : 0.95
        }
    }

    return null
}

export async function triggerSystemWebhook(webhookId: string, payload: any) {
    // Simulate webhook trigger
    await new Promise(resolve => setTimeout(resolve, 1000))
    console.log(`Triggered webhook ${webhookId} with payload`, payload)
    return { success: true, timestamp: new Date().toISOString() }
}
